// AUTO-GEN TOOL (빌드 타임 전용) — 24절기 절입 시각 테이블 생성.
//
// 알고리즘: astronomy-engine(MIT, 오프라인)의 SearchSunLongitude —
//   태양 겉보기 황경(視黃經, 진분점 기준)이 목표각(15° 배수)에 도달하는 순간을 구한다.
//   이는 절기의 정의 그 자체이며, KASI(한국천문연구원) 공인값과 같은 기준이다.
//   (구현 전 Meeus 저차 근사는 KASI 대비 최대 ±14분 오차 → 절입 경계 출생의 월주 오판 위험)
//
// 정확도 근거: `solar-terms.usno.test.ts`가 USNO 공표 분점·지점(2016~2036, 84건)과
//   1분 이내 일치를 상시 검증한다. KASI API 대조(verify-solar-terms.ts)에서도
//   불일치는 ±1분(KASI의 분 단위 표기 차이)뿐이었다.
// 절입 시각은 **초 단위로 저장**한다 — 분 단위로 반올림하면 절입과 같은 분에 태어난 사람의
//   월주가 반올림 방향에 따라 뒤집힌다. 초까지 두면 경계 판정에 해석의 여지가 없다.
//
// 실행: npx tsx scripts/gen-solar-terms.ts
import { writeFileSync } from "node:fs";
import * as Astronomy from "astronomy-engine";

const YEAR_FROM = 1900;
const YEAR_TO = 2100;

// 인덱스 순서(0=소한 … 23=동지)와 근사 절입일 시드(month, day).
// 목표 황경 = (285 + 15*index) % 360
const SEED: [number, number][] = [
  [1, 6], [1, 20], [2, 4], [2, 19], [3, 6], [3, 21], [4, 5], [4, 20],
  [5, 6], [5, 21], [6, 6], [6, 21], [7, 7], [7, 23], [8, 8], [8, 23],
  [9, 8], [9, 23], [10, 8], [10, 23], [11, 7], [11, 22], [12, 7], [12, 22],
];

const p2 = (n: number) => String(n).padStart(2, "0");

/** 절대 시각(UTC) → KST 벽시계 "YYYY-MM-DDTHH:mm:ss". 초 반올림은 epoch에서 처리해 시·일 이월이 자동. */
function toKstWallClock(utc: Date): string {
  const ms = Math.round((utc.getTime() + 9 * 3600_000) / 1000) * 1000;
  const d = new Date(ms);
  return (
    `${d.getUTCFullYear()}-${p2(d.getUTCMonth() + 1)}-${p2(d.getUTCDate())}` +
    `T${p2(d.getUTCHours())}:${p2(d.getUTCMinutes())}:${p2(d.getUTCSeconds())}`
  );
}

/** 절기 k(0=소한…23=동지)의 절입 절대 시각. 태양 황경은 단조 증가라 시드 ±수일 안에 유일해. */
function termInstant(year: number, k: number): Date {
  const targetLon = (285 + k * 15) % 360;
  const [sm, sd] = SEED[k];
  const start = new Date(Date.UTC(year, sm - 1, sd - 4));
  const t = Astronomy.SearchSunLongitude(targetLon, start, 10);
  if (!t) throw new Error(`${year}년 절기 ${k}(황경 ${targetLon}°) 탐색 실패`);
  return t.date;
}

const rows: string[] = [];
for (let y = YEAR_FROM; y <= YEAR_TO; y++) {
  const terms: string[] = [];
  for (let k = 0; k < 24; k++) terms.push(toKstWallClock(termInstant(y, k)));
  rows.push(`  ${y}: [${terms.map((t) => `"${t}"`).join(",")}],`);
}

writeFileSync(
  "src/lib/engine/solar-terms.data.ts",
  `// AUTO-GENERATED by scripts/gen-solar-terms.ts — DO NOT EDIT BY HAND.\n` +
    `// 손으로 고치지 말고 생성기를 고쳐 재생성할 것. 값의 근거는 astronomy-engine(태양 겉보기 황경)이며,\n` +
    `// solar-terms.usno.test.ts(USNO 공표 분점·지점 대조)와 verify-solar-terms.ts(KASI 대조)가 검증한다.\n` +
    `// KST(UTC+9) 절입 시각(초 단위). 인덱스 0=소한,1=대한,2=입춘,3=우수,4=경칩,5=춘분,\n` +
    `//   6=청명,7=곡우,8=입하,9=소만,10=망종,11=하지,12=소서,13=대서,14=입추,\n` +
    `//   15=처서,16=백로,17=추분,18=한로,19=상강,20=입동,21=소설,22=대설,23=동지\n` +
    `export const SOLAR_TERMS: Record<number, string[]> = {\n${rows.join("\n")}\n};\n`,
  "utf8",
);

console.log(`생성 완료: ${YEAR_FROM}~${YEAR_TO} (${rows.length}개 연도 × 24절기)`);
